import { EventEmitter } from '@angular/core';
import { UntypedFormControl } from "@angular/forms";
import { MatTableDataSource } from "@angular/material/table";
import { FhirValidatorService } from "../services/fhir-validator.service";
import { ValidationResults } from "../modal/validation-results";
import { ApiResponse } from "../modal/api-response";
import { ValidatorInput } from "../modal/validator-input-format";
import * as i0 from "@angular/core";
export type SubmitButtonAlignment = 'left' | 'right';
export declare class NgxFhirValidatorComponent {
    private fhirValidatorService;
    validatorTitle: string;
    validationResultsExpanded: boolean;
    resultDetailsExpandBtnShown: boolean;
    formatResourceBtnShown: boolean;
    clearValidatorBtnShown: boolean;
    submitBtnShown: boolean;
    exportResultsButtonShown: boolean;
    submitBtnTitle: string;
    validationInputFormat: ValidatorInput;
    maxFileSize: number;
    submitBtnAlignment: SubmitButtonAlignment;
    cancelValidationBtnShown: boolean;
    buttonTxtColor: string;
    buttonBackgroundColor: string;
    exportValidationResultsBtnName: string;
    onValidation: EventEmitter<ValidationResults>;
    onApiError: EventEmitter<any>;
    onResourceContentChanged: EventEmitter<any>;
    onExportValidationResults: EventEmitter<any>;
    inputRef: any;
    apiResponse: ApiResponse | null;
    fhirResource: string;
    resourceFormat: string;
    fileName: string;
    validationErrorStr: string;
    hasResponseData: boolean;
    parsedFhirResource: string;
    displayedColumns: string[];
    isLoading: boolean;
    allExpanded: boolean;
    severityLevels: string[];
    severityLevelsFormControl: UntypedFormControl;
    dataSource: MatTableDataSource<any>;
    validationFinished: boolean;
    isValidResource: boolean;
    serverErrorDetected: boolean;
    serverErrorList: any[];
    serverErrorStatus: string;
    lines: number;
    width: number;
    serverTimoutDetected: boolean;
    SERVER_TIMEOUT_INTERVAL: number;
    constructor(fhirValidatorService: FhirValidatorService);
    formatFhirResource(): void;
    lineNumbers(): void;
    getLineNumbers(): string[];
    onFormatInput(): void;
    clearUI(): void;
    onClear(): void;
    onFileSelected(event: any): void;
    validateFhirResource(fhirResource?: any, resourceFormat?: string): void;
    onPasteFhirResource(event: ClipboardEvent): void;
    getLineNumbersBySeverity(apiResponse: ApiResponse | null, severity: string): number[];
    scrollToElement(location: string): void;
    getLineNumberFromLocation(locationStr: string): number;
    onLocationSelected(response: any): void;
    private executeAPIValidation;
    toggle(): void;
    onFilterResults(): void;
    getFilterPredicate(): (row: any, filters: string) => boolean;
    onCancelValidation(): void;
    checkExpandCollapseAllStatus(): void;
    isFilterEnabled(severity: string): boolean;
    getCount(level: any): number;
    onCloseServerErrorMessage(): void;
    private setValidatorResponse;
    clearValidationErrors(): void;
    getLineItemClass(item: string, i: number): "" | "error-mark" | "warning-mark" | "info-mark" | "note-mark";
    exportValidationResults(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<NgxFhirValidatorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NgxFhirValidatorComponent, "lib-ngx-fhir-validator", never, { "validatorTitle": { "alias": "validatorTitle"; "required": false; }; "validationResultsExpanded": { "alias": "validationResultsExpanded"; "required": false; }; "resultDetailsExpandBtnShown": { "alias": "resultDetailsExpandBtnShown"; "required": false; }; "formatResourceBtnShown": { "alias": "formatResourceBtnShown"; "required": false; }; "clearValidatorBtnShown": { "alias": "clearValidatorBtnShown"; "required": false; }; "submitBtnShown": { "alias": "submitBtnShown"; "required": false; }; "exportResultsButtonShown": { "alias": "exportResultsButtonShown"; "required": false; }; "submitBtnTitle": { "alias": "submitBtnTitle"; "required": false; }; "validationInputFormat": { "alias": "validationInputFormat"; "required": false; }; "maxFileSize": { "alias": "maxFileSize"; "required": false; }; "submitBtnAlignment": { "alias": "submitBtnAlignment"; "required": false; }; "cancelValidationBtnShown": { "alias": "cancelValidationBtnShown"; "required": false; }; "buttonTxtColor": { "alias": "buttonTxtColor"; "required": false; }; "buttonBackgroundColor": { "alias": "buttonBackgroundColor"; "required": false; }; "exportValidationResultsBtnName": { "alias": "exportValidationResultsBtnName"; "required": false; }; }, { "onValidation": "onValidation"; "onApiError": "onApiError"; "onResourceContentChanged": "onResourceContentChanged"; "onExportValidationResults": "onExportValidationResults"; }, never, never, false, never>;
}
